// src/icons/fontawesome.ts
// src/icons/fontawesome.ts
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBell,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faHeart,
  faStar,
  faUser,
  faEdit,
  faSignOutAlt,
  faGem,
  faShoppingBag,
  faBox,
  faLaptop,
  faMobile,
  faCog,
  faQuestion,
  faTags,
  faHome,
  faTrash,
  faTableCells,
  faGrip,
  faSquare,
  faBars,
  faChartLine,
  faArrowTrendUp,
  faArrowTrendDown,
  faArrowRightArrowLeft,
  faUserAlt,
  faMoneyBill,
} from "@fortawesome/free-solid-svg-icons";
import { faHeart as farHeart, faBell as farBell } from "@fortawesome/free-regular-svg-icons";

library.add(
  faBell,
  farBell,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faHeart,
  farHeart,
  faStar,
  faUser,
  faEdit,
  faSignOutAlt,
  faGem,
  faShoppingBag,
  faBox,
  faLaptop,
  faMobile,
  faCog,
  faQuestion,
  faTags,
  faHome,
  faTrash,
  faTableCells,
  faGrip,
  faSquare,
  faBars,
  faChartLine,
  faArrowTrendUp,
  faArrowTrendDown,
  faArrowRightArrowLeft,
  faUserAlt,
  faMoneyBill,
);

